version : "3"


services:
  web:
    build:
      context: .
      dockerfile: django_docker_file
    container_name: url_shortener
    volumes:
      - ./:/docker-compose.yml
    ports:
      - "8000:8000"
    command: sh -c "python3 manage.py migrate & python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db
      - cache

  db:
    image: postgres:latest
    container_name: shortener_db
    env_file:
      - .env
    environment:
      - LANG:'ja_JP.UTF-8'
      - LANGUAGE:'ja_JP.UTF-8'
      - LC_ALL:'ja_JP.UTF-8'

  adminer:
    image: adminer:latest
    container_name: shortener_adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

