version : "3"


services:
  web:
    build:
      context: ./src/urlshortener/
      dockerfile: Dockerfile
    command: gunicorn urlshortener.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: shortener_db
    env_file:
      - .env
    environment:
      - LANG:'ja_JP.UTF-8'
      - LANGUAGE:'ja_JP.UTF-8'
      - LC_ALL:'ja_JP.UTF-8'


